stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-17
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-inn-reach:volaris-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-bxflg:volaris-helmcharts-mod-inn-reach
      version: 0.1.4
      answers:
        image.repository: docker.dev.folio.org/mod-inn-reach
        image.tag: volaris-${CICD_EXECUTION_SEQUENCE}
        postJob.enabled: true
      targetNamespace: volaris
      name: mod-inn-reach
timeout: 60
notification: {}
