ALTER TABLE item_contribution_options_configuration ADD COLUMN id UUID;
ALTER TABLE item_contribution_options_configuration DROP CONSTRAINT item_contribution_options_configuration_pkey CASCADE;
ALTER TABLE item_contribution_options_configuration ADD CONSTRAINT pk_item_contribution_options_configuration PRIMARY KEY (id);

ALTER TABLE not_available_item_status ADD CONSTRAINT fk_not_available_item_status_item_contribution_options_configuration
FOREIGN KEY (item_contribution_options_configuration_id) REFERENCES item_contribution_options_configuration (id) ON DELETE CASCADE;
ALTER TABLE non_lendable_loan_type ADD CONSTRAINT fk_non_lendable_loan_type_item_contribution_options_configuration
FOREIGN KEY (item_contribution_options_configuration_id) REFERENCES item_contribution_options_configuration (id) ON DELETE CASCADE;
ALTER TABLE non_lendable_location ADD CONSTRAINT fk_non_lendable_location_item_contribution_options_configuration
FOREIGN KEY (item_contribution_options_configuration_id) REFERENCES item_contribution_options_configuration (Id) ON DELETE CASCADE;
ALTER TABLE non_lendable_material_type ADD CONSTRAINT fk_non_lendable_material_type_item_contribution_options_configuration
FOREIGN KEY (item_contribution_options_configuration_id) REFERENCES item_contribution_options_configuration (id) ON DELETE CASCADE;
