server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/modinreach
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
debug: off
