openapi: 3.0.0
info:
  title: INN-Reach API
  version: v1
servers:
  - url: /inn-reach/
paths:
  /central-servers/{centralServerId}/material-type-mappings:
    get:
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/materialTypeMappingsDTO"
        '400':
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
      description: Get a list of material type mappings for the given central server
      operationId: getMaterialTypeMappingsByServerId
      parameters:
        - $ref: "#/components/parameters/centralServerId"
        - $ref: "#/components/parameters/trait_pageable_offset"
        - $ref: "#/components/parameters/trait_pageable_limit"
    post:
      responses:
        '201':
          description: Material type mapping created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/materialTypeMappingDTO"
        '400':
          description: Bad request
          content:
            application/json:
              example:
                $ref: "#/components/examples/error"
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
      description: Add new material type mapping associated with the central server
      operationId: postMaterialTypeMapping
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/materialTypeMappingDTO"
        required: true
      parameters:
        - $ref: "#/components/parameters/centralServerId"
  /central-servers/{centralServerId}/material-type-mappings/{id}:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/materialTypeMappingDTO"
        '404':
          description: Material type mapping not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
      description: Get material type mapping by id
      operationId: getMaterialTypeMappingById
      parameters:
        - $ref: "#/components/parameters/centralServerId"
        - $ref: "#/components/parameters/id"
    put:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/materialTypeMappingDTO"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/validationErrorsDTO"
        '404':
          description: Material type mapping not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
      description: Update material type mapping
      operationId: updateMaterialTypeMapping
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/materialTypeMappingDTO"
        required: true
      parameters:
        - $ref: "#/components/parameters/centralServerId"
        - $ref: "#/components/parameters/id"
    delete:
      responses:
        '204':
          description: No content
        '404':
          description: Material type mapping not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
      description: Delete material type mapping
      operationId: deleteMaterialTypeMapping
      parameters:
        - $ref: "#/components/parameters/centralServerId"
        - $ref: "#/components/parameters/id"
  /locations:
    post:
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/innReachLocationDTO"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/validationErrorsDTO"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
      description: Add new InnReach location
      operationId: postInnReachLocation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/innReachLocationDTO"
        required: true
    get:
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/innReachLocationsDTO"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
      description: Get a list of InnReach locations
      operationId: getLocations
      parameters:
        - $ref: "#/components/parameters/trait_pageable_offset"
        - $ref: "#/components/parameters/trait_pageable_limit"
  /locations/{locationId}:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/innReachLocationDTO"
        '404':
          description: InnReach location not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
      description: Get InnReach location by id
      operationId: getLocationById
      parameters:
        - $ref: '#/components/parameters/id'
    put:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/innReachLocationDTO"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/validationErrorsDTO"
        '404':
          description: InnReach location not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
      description: Update InnReach location
      operationId: updateLocation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/innReachLocationDTO"
        required: true
      parameters:
        - $ref: '#/components/parameters/id'
    delete:
      responses:
        '204':
          description: No content
        '404':
          description: InnReach location not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
      description: Delete InnReach location
      operationId: deleteLocation
      parameters:
        - $ref: '#/components/parameters/id'
components:
  schemas:
    UUID:
      type: string
      format: uuid
    innReachLocationDTO:
      $ref: schemas/innReachLocationDTO.json
    innReachLocationsDTO:
      $ref: schemas/innReachLocationsDTO.json
    validationErrorsDTO:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        validationErrors:
          type: array
          items:
            $ref: schemas/validationErrorDTO.json
    materialTypeMappingDTO:
      $ref: schemas/materialTypeMappingDTO.json
    materialTypeMappingsDTO:
      $ref: schemas/materialTypeMappingsDTO.json
    error:
      $ref: schemas/error.json
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/UUID"
    centralServerId:
      name: centralServerId
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/UUID"
    trait_queryable_query:
      name: query
      in: query
      description: A query string to filter rules based on matching criteria in fields.
      schema:
        type: string
    trait_pageable_offset:
      name: offset
      in: query
      description: Skip over a number of elements by specifying an offset value for the query
      schema:
        default: 0
        minimum: 0
        maximum: 2147483647
        type: integer
    trait_pageable_limit:
      name: limit
      in: query
      description: Limit the number of elements returned in the response
      schema:
        default: 10
        minimum: 0
        maximum: 2147483647
        type: integer
  examples:
    error:
      value:
        $ref: examples/error.sample