package org.folio.innreach.domain.service;

import org.folio.innreach.dto.ItemContributionOptionsConfigurationDTO;

import java.util.UUID;

public interface ItemContributionOptionsConfigurationService {
  ItemContributionOptionsConfigurationDTO getItmContribOptConf(UUID centralServerId);

  ItemContributionOptionsConfigurationDTO createItmContribOptConf(ItemContributionOptionsConfigurationDTO itmContribOptConfDTO);

  ItemContributionOptionsConfigurationDTO updateItmContribOptConf(ItemContributionOptionsConfigurationDTO itmContribOptConfDTO);
}
